# we are using separate workflow because CI producing test binaries with CPPFLAGS=-DTESTMODE

name: Eskenas qt build - Windows cross compile 20.04


on:
  push:
    branches:
    - eskenas


jobs:

  windows-build:
    name: Windows Build (mingw)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install deps (Windows)
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get upgrade -y
          sudo apt-get install mingw-w64 build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool libncurses-dev unzip git python zlib1g-dev wget bsdmainutils automake libboost-all-dev libssl-dev libprotobuf-dev protobuf-compiler libqrencode-dev libdb++-dev ntp ntpdate nano software-properties-common curl libevent-dev libcurl4-gnutls-dev cmake clang libsodium-dev -y
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      - name: Build (Windows)
        run: |
          ./zcutil/build-qt-win.sh -j$(nproc)
          zip --junk-paths eskenas-qt-win eskenas-qt-win
      - name: Upload eskenas-qt-win.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: eskenas-qt-win
          path: ./eskenas-qt-win.zip
