# we are using separate workflow because CI producing test binaries with CPPFLAGS=-DTESTMODE

name: Eskenas cli build - MacOS 10.15 Catalina


on:
  push:
    branches:
    - eskenas


jobs:

  osx-build:
    name: OSX Build
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install deps (macOS)
        run: |
          brew update
          brew upgrade
          brew tap discoteq/discoteq; brew install flock
          brew install autoconf autogen automake
          brew install gcc@8
          brew install binutils
          brew install protobuf
          brew install coreutils
          brew install wget
          brew install python3
      - name: Build (macOS)
        run: |
          ./zcutil/build-mac.sh -j4
          zip --junk-paths eskenas-osx src/eskenasd src/eskenas-cli
      - name: Upload eskenas-osx.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: eskenas-osx
          path: ./eskenas-osx.zip
